"""
make_fixture_log.py

Generates test_logs/Player_Old_Draft.log from the existing test fixtures
so the simulator can run on Mac (where Arena doesn't produce a real log).

Usage:
    python make_fixture_log.py
Then:
    python simulator.py
"""

import os
import sys

TARGET_DIR = "test_logs"
TARGET_FILE = os.path.join(TARGET_DIR, "Player_Old_Draft.log")


def main():
    # Import test data (real Arena log lines captured from live drafts)
    sys.path.insert(0, os.path.dirname(__file__))
    from tests.test_log_scanner_data import (
        TDM_PREMIER_DRAFT_ENTRIES_2025_4_8,
        OTJ_PREMIER_DRAFT_ENTRIES_2024_5_7,
        MKM_PREMIER_DRAFT_ENTRIES,
    )

    os.makedirs(TARGET_DIR, exist_ok=True)

    lines = [
        "[UnityCrossThreadLogger] --- Fixture log generated by make_fixture_log.py ---\n",
    ]

    # Write a full TDM Premier Draft sequence
    print("Building TDM PremierDraft entries...")
    for label, _result, log_line in TDM_PREMIER_DRAFT_ENTRIES_2025_4_8:
        print(f"  + {label}")
        lines.append(log_line + "\n")

    # Then an OTJ Premier Draft sequence
    print("Building OTJ PremierDraft entries...")
    for label, _result, log_line in OTJ_PREMIER_DRAFT_ENTRIES_2024_5_7:
        print(f"  + {label}")
        lines.append(log_line + "\n")

    # Then MKM
    print("Building MKM entries...")
    for label, _result, log_line in MKM_PREMIER_DRAFT_ENTRIES:
        print(f"  + {label}")
        lines.append(log_line + "\n")

    with open(TARGET_FILE, "w", encoding="utf-8") as f:
        f.writelines(lines)

    print(f"\nWrote {len(lines)} lines to {TARGET_FILE}")
    print("\nNow run:  python simulator.py")
    print("And in another terminal:  python main.py")


if __name__ == "__main__":
    main()
